services:
  waha:
    image: devlikeapro/waha:latest
    container_name: waha
    restart: always
    ports:
      - '3000:3000'
    environment:
      - WHATSAPP_DEFAULT_ENGINE=NOWEB

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    environment:
      - WEBHOOK_URL=http://n8n:5678
    ports:
      - '5678:5678'
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
