services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # Change the HTTP and HTTPS ports to avoid conflict with Apache
      - '8080:80'  # Public HTTP Port
      - '8443:443'  # Public HTTPS Port
      - '81:81'  # Admin Web Port (keeping it the same)

    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
